[package]
name = "hemlock-config"
description = "Curly-brace hierarchical config: lexer, parser, tree types, diff"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
thiserror = { workspace = true }

[lints]
workspace = true
