[package]
name = "hemlock-installer"
description = "ONIE installer: machine.conf verification, disk selection TUI, GRUB install"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
hemlock-common = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
hemlock-platform = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
